### ISSUE TITLE
Error line 421, sometimes the id is outside the info index

### ISSUE THREAD

**Issue by NotAnyMike** [NotAnyMike/HRL#23]
No clues yet why this is happening. The problem is because the  index of the info[id] is outside info, but id comes from self.track, thus somewhat info is smaller or somewhere info is getting shrinked

Ideas:
- [x] Check if info and track have different sizes

**Comment by NotAnyMike** [comment]
the error is

    Traceback (most recent call last):
      File "hrl/common/run_experiment.py", line 217, in <module>
        run_experiment(**args)
      File "hrl/common/run_experiment.py", line 132, in run_experiment
        callback=callback,
      File "/hdd/Documents/stable-baselines-HRL/stable_baselines/ppo2/ppo2.py", line 294, in learn
        obs, returns, masks, actions, values, neglogpacs, states, ep_infos, true_reward = runner.run()
      File "/hdd/Documents/stable-baselines-HRL/stable_baselines/ppo2/ppo2.py", line 434, in run
        self.obs[:], rewards, self.dones, infos = self.env.step(clipped_actions)
      File "/hdd/Documents/stable-baselines-HRL/stable_baselines/common/vec_env/base_vec_env.py", line 94, in step
        return self.step_wait()
      File "/hdd/Documents/stable-baselines-HRL/stable_baselines/common/vec_env/dummy_vec_env.py", line 36, in step_wait
        self.envs[env_idx].step(self.actions[env_idx])
      File "/hdd/Documents/HRL/hrl/envs/env.py", line 201, in step
        s,r,d,_ = super(Turn_left,self).step(action)
      File "/hdd/Documents/gym2/gym/envs/box2d/car_racing.py", line 1264, in step
        self.world.Step(1.0/FPS, 6*30, 2*30)
      File "/hdd/Documents/gym2/gym/envs/box2d/car_racing.py", line 149, in BeginContact
        self._contact(contact, True)
      File "/hdd/Documents/gym2/gym/envs/box2d/car_racing.py", line 172, in _contact
        self.reward_callback(tile, obj, begin, locals(), globals())
      File "/hdd/Documents/HRL/hrl/envs/env.py", line 33, in reward_fn
        self.env.add_current_tile(tile.id, tile.lane)
      File "/hdd/Documents/gym2/gym/envs/box2d/car_racing.py", line 420, in add_current_tile
        if self.info[id]['track'] > 0:
    IndexError: index 312 is out of bounds for axis 0 with size 294

**Comment by NotAnyMike** [comment]
Current solution is to catch the error, print the msg and return None, this **has** to be removed

**Comment by NotAnyMike** [comment]
I think the error does not have to do with smaller info, **but the id is not correct**, in all cases so far have the same lenght

**Comment by NotAnyMike** [comment]
It can be related to a problem filtering correctly the id of a object in the contact listener

**Comment by NotAnyMike** [comment]
It has not occurred again.
